const fs = require('fs');

let content = fs.readFileSync('src/data/products.js', 'utf-8');

// 1. Add models property to existing products
content = content.replace(/compatibility: \[([^\]]*)\],/g, (match, p1) => {
  return match + '\n    models: [' + p1 + '],';
});

// 2. Add 'body-parts' to categories
content = content.replace("{ key: 'all',", "{ key: 'body-parts', label: 'Body Parts', count: products.filter((p) => p.category === 'body-parts').length },\n  { key: 'all',");

// 3. New products data based on images
const newProductsStr = `
  {
    id: 13,
    slug: 'meter-flap-rayz-110',
    name: 'Meter Flap for Yamaha RAYZ 110',
    shortName: 'Meter Flap (RAYZ)',
    price: 350,
    originalPrice: 450,
    discount: 22,
    rating: 4,
    reviews: 8,
    category: 'body-parts',
    badge: 'NEW',
    images: ['/images/1.png'],
    features: ['Genuine Yamaha Part', 'Part No: 1GCF6145'],
    compatibility: ['Yamaha RAYZ 110'],
    models: ['RAYZ 110'],
    colors: ['Common'],
    description: 'Genuine Yamaha meter flap for RAYZ 110. Common color part. Part number: 1GCF6145.',
    inStock: true,
    isBestSeller: false,
    isNew: true,
  },
  {
    id: 14,
    slug: 'windshield-rayz-110',
    name: 'Windshield for Yamaha RAYZ 110',
    shortName: 'Windshield (RAYZ)',
    price: 450,
    originalPrice: 500,
    discount: 10,
    rating: 5,
    reviews: 15,
    category: 'body-parts',
    badge: null,
    images: ['/images/1.png'],
    features: ['Genuine Yamaha Part', 'Part No: 2NCF8381'],
    compatibility: ['Yamaha RAYZ 110'],
    models: ['RAYZ 110'],
    colors: ['Common'],
    description: 'Genuine Yamaha windshield for RAYZ 110. Part number: 2NCF8381.',
    inStock: true,
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 15,
    slug: 'meter-flap-rayzr110',
    name: 'Meter Flap for Yamaha RAYZR110',
    shortName: 'Meter Flap (RAYZR)',
    price: 380,
    originalPrice: 480,
    discount: 20,
    rating: 4,
    reviews: 10,
    category: 'body-parts',
    badge: null,
    images: ['/images/2.png'],
    features: ['Genuine Yamaha Part', 'Part No: B62F614500'],
    compatibility: ['Yamaha RAYZR110'],
    models: ['RAYZR110'],
    colors: ['Common'],
    description: 'Genuine Yamaha meter flap for RAYZR110. Part number: B62F614500.',
    inStock: true,
    isBestSeller: false,
    isNew: false,
  },
  {
    id: 16,
    slug: 'battery-box-plate-rayzr110',
    name: 'Battery Box Plate for Yamaha RAYZR110',
    shortName: 'Battery Plate (RAYZR)',
    price: 250,
    originalPrice: 300,
    discount: 16,
    rating: 4,
    reviews: 5,
    category: 'body-parts',
    badge: null,
    images: ['/images/2.png'],
    features: ['Genuine Yamaha Part', 'Part No: B62F839R00'],
    compatibility: ['Yamaha RAYZR110'],
    models: ['RAYZR110'],
    colors: ['Common'],
    description: 'Genuine Yamaha battery box plate for RAYZR110. Part number: B62F839R00.',
    inStock: true,
    isBestSeller: false,
    isNew: false,
  },
  {
    id: 17,
    slug: 'tailpanel-rayz-110-white-black',
    name: 'Tailpanel Set for Yamaha RAYZ 110 (White & Black)',
    shortName: 'Tailpanel (RAYZ)',
    price: 850,
    originalPrice: 1000,
    discount: 15,
    rating: 5,
    reviews: 21,
    category: 'body-parts',
    badge: 'POPULAR',
    images: ['/images/3.png'],
    features: ['Genuine Yamaha Part', 'RH: B81XF17210P5', 'LH: B81XF17110P5'],
    compatibility: ['Yamaha RAYZ 110'],
    models: ['RAYZ 110'],
    colors: ['White & Black'],
    description: 'Genuine Yamaha Tailpanel Set (Left & Right) for RAYZ 110 in White & Black color scheme.',
    inStock: true,
    isBestSeller: true,
    isNew: false,
  },
  {
    id: 18,
    slug: 'handle-cover-upper-rayz-110',
    name: 'Handle Cover Upper for Yamaha RAYZ 110',
    shortName: 'Handle Cover (RAYZ)',
    price: 550,
    originalPrice: 650,
    discount: 15,
    rating: 4,
    reviews: 9,
    category: 'body-parts',
    badge: null,
    images: ['/images/4.png'],
    features: ['Genuine Yamaha Part', 'Part No: 2NCF614300P1'],
    compatibility: ['Yamaha RAYZ 110'],
    models: ['RAYZ 110'],
    colors: ['Red & Black', 'White & Black'],
    description: 'Genuine Yamaha Handle Cover Upper for RAYZ 110. Fits White & Black, Red & Black models.',
    inStock: true,
    isBestSeller: false,
    isNew: false,
  },
  {
    id: 19,
    slug: 'mudguard-rayz-110-cyan-black',
    name: 'Front Mudguard for Yamaha RAYZ 110 (Cyan & Black)',
    shortName: 'Mudguard (RAYZ)',
    price: 750,
    originalPrice: 850,
    discount: 11,
    rating: 4,
    reviews: 14,
    category: 'body-parts',
    badge: null,
    images: ['/images/5.png'],
    features: ['Genuine Yamaha Part', 'Part No: 1GCXF15130P8'],
    compatibility: ['Yamaha RAYZ 110'],
    models: ['RAYZ 110'],
    colors: ['Cyan & Black'],
    description: 'Genuine Yamaha Front Mudguard for RAYZ 110 in Cyan & Black color scheme.',
    inStock: true,
    isBestSeller: false,
    isNew: false,
  },
  {
    id: 20,
    slug: 'side-panel-rayz-110-blue-white',
    name: 'Side Panel Set for Yamaha RAYZ 110 (Blue & White)',
    shortName: 'Side Panel (RAYZ)',
    price: 950,
    originalPrice: 1100,
    discount: 13,
    rating: 5,
    reviews: 25,
    category: 'body-parts',
    badge: 'HOT',
    images: ['/images/6.png'],
    features: ['Genuine Yamaha Part', 'RH: B81XF83G30P7', 'LH: B81XF83630P7'],
    compatibility: ['Yamaha RAYZ 110'],
    models: ['RAYZ 110'],
    colors: ['Blue & White'],
    description: 'Genuine Yamaha Side Panel Set (Left & Right) for RAYZ 110 in Blue & White color scheme.',
    inStock: true,
    isBestSeller: true,
    isNew: false,
  },
`;

content = content.replace('];\n\n// Utility helpers', newProductsStr + '];\n\n// Utility helpers');

// 4. Add extract unique models helper at the bottom
const modelsHelper = `
export const bikeModels = [...new Set(products.flatMap(p => p.models || []))].sort();
`;
content += modelsHelper;

fs.writeFileSync('src/data/products.js', content);
